server:
  port: 8081
spring:
  application:
    name: fgw-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.110.241:3306/fgw?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  mvc:
    date-format: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#yml配置
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
  file:
    path: /mysoft/fgw/log

fgw:
  log:
    max-length: 300
  max-inactive-interval: 86400
  file-path: /mysoft/fgw/appendix
  token:
    store: true
    store-path: /mysoft/fgw/tokens

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
