server:
  port: 8081
spring:
  application:
    name: fgw-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fgw?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 111111
  mvc:
    date-format: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
logging:
  level:
    com.pxxy: info